# From https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/skeletons/tekton/tekton/pipelinerun.yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: testrepoimx2j-b0d21d3
  namespace: orchestrator-gitops
  labels:
    backstage.io/kubernetes-id: testrepoimx2j-ci
spec:
  params:
    - name: gitUrl
      value: git@github.com:orchestrator-test/testrepoimx2j.git
    - name: gitOpsUrl
      value: git@github.com:orchestrator-test/testrepoimx2j-gitops.git
    - name: workflowId
      value: testrepoimx2j
    - name: convertToFlat
      value: 'true'
    - name: quayOrgName
      value: orchestrator-test
    - name: quayRepoName
      value: orchestrator-qe-ci
    - name: gitHost
      value: github.com
  pipelineRef:
    name: workflow-deployment
  workspaces:
    - name: workflow-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: workflow-gitops
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials

    - name: ssh-creds
      secret:
        secretName: github-ssh-credentials
