apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testrepoimx2j-gitops
  namespace: orchestrator-gitops
  labels:
    app-type: workflow
    app: testrepoimx2j
    rht-gitops.com/janus-argocd: testrepoimx2j-gitops
spec:
  destination:
    namespace: sonataflow-infra
    server: https://kubernetes.default.svc
  project: orchestrator-gitops
  source:
    path: ./kustomize/base
    repoURL: git@github.com:orchestrator-test/testrepoimx2j-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
